baseURL: https://gavencao.netlify.app/
languageCode: en-us
title: Portfolio website for Guanwen Cao
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Shanghai - Hong Kong - New York - Los Angeles - London
    title: Hi, my name is Guanwen Cao
  blog: {}
  contact: 
    address:
      - city: London, W2 1GN 
        country: United Kindom
        street: 287 Edware Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: gcao.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+86) 13795436891
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
   #   - icon: fa-twitter
   #     label: Twitter
    #    url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Things About Me
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Business Experiences
        url: blogs
      - name: Interests
        url: blogs/magna
      - name: R Programming
        url: blogs/ipsum
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Business Experiences
        title: PwC
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Business Experiences
        title: CICC Capital
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Interests
        title: Movie
        url: blogs/magna
      - image: pic04.jpg
        subtitle: R Programming
        title: Data Analysis
        url: blogs/ipsum

  two:
    buttonText: More abpout me
    enable: yes
    subtitle: "Hi, my name is Guanwen Cao. I have lived in five different cities which include Shanghai, Hong Kong, New York City, Los Angeles and London. I have got a multicultural exposures so I am looking forward to make friends who are from different culture background. "
    title: About Me
    url: blogs
